### ISSUE TITLE
Variable view shows syntax error

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-python-web-wasm#27]
<img width="761" alt="image" src="https://user-images.githubusercontent.com/1931590/204256123-a9c692bc-e3af-460a-a909-01cb0a1d62f5.png">

**Comment by dbaeumer** [comment]
Stepping over the statement then correctly shows:
<img width="755" alt="image" src="https://user-images.githubusercontent.com/1931590/204256275-92d17ce7-b09c-4c12-9eca-cc3d885b2495.png">

**Comment by rchiodo** [comment]
Super weird. Must be a parsing error from the `__dirs__` result.
