### ISSUE TITLE
Debug always stop in the first line

### ISSUE THREAD

**Issue by paulacamargo25** [microsoft/vscode-python-web-wasm#33]
Testing https://github.com/microsoft/vscode/issues/167433

When i debug a python file, the debug process stop always at the first line, even if i don't have a breakpoint there. It should only stop where I have breakpoints set.

<img width="1205" alt="Screenshot 2022-11-29 at 3 38 08 PM" src="https://user-images.githubusercontent.com/17892325/204680829-bc597494-e49b-4c58-acfe-524df178bc5b.png">

**Comment by rchiodo** [comment]
This is on purpose. `stopOnEntry` defaults to true for the pdb based debugger.

You can change this by creating a launch.json that specifies stopOnEntry as false.

**Comment by rchiodo** [comment]
The reason I made 'stopOnEntry' as true the default because of the thought that this would be used by people unfamiliar with debugging. The assumption being novice users wouldn't even know what a breakpoint was.

**Comment by dbaeumer** [comment]
I actually like the behavior as well since users can't set breakpoints when the code runs due to the limitations we have with pdb.
